# These are supported funding model platforms

patreon: https://www.patreon.com/aorlconsult
open_collective: https://opencollective.com/aorlovsky
ko_fi: https://ko-fi.com/orlovskyconsultinggbr
liberapay: https://liberapay.com/aorlovsky/
lfx_crowdfunding: https://crowdfunding.lfx.linuxfoundation.org/projects/e52690f6-a013-4120-a6b6-6f872653dbec
buy_me_a_coffee:  https://buymeacoffee.com/aorlovsky
Support us via crypto:

**BTC: bc1qzfjtuxc6e68kzfaexr995xtu5xjtyzmtuukvz6**
**ETH: 0x89895850C2346EBE3a0d693be8c7d9a52A58f15E**
**Stellar: GCK4O37GEXYR3K6GU5NARW3CD5PRYDYE2WHWITVRJOKYPNIJJC6JM7ZK**

